version: '2'

services:
  app:
    image: 'skodentsev/task:latest'
    container_name: app
    depends_on:
      - mongodb
    ports:
    - 8090:8090
    env_file:
      - ./task.env
    environment:
      - DB_HOST=mongodb

  mongodb:
    image: 'mongo:4.4.3'
    container_name: mongodb
    ports:
    - 27017:27017